=== Yogesh111994/APITestingFramework2024/src/test/resources/structuremetricsdeepdive.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "aop": {
      "type": "object",
      "properties": {
        "legend": {
          "type": "object",
          "properties": {
            "data": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "data"
          ]
        },
        "series": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "data": {
                "type": "array",
                "items": {
                  "type": "number"
                }
              },
              "values": {
                "type": "array",
                "items": {}
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "data",
              "values",
              "type"
            ]
          }
        },
        "xaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "type",
            "data"
          ]
        },
        "yaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "type",
            "data"
          ]
        }
      },
      "required": [
        "legend",
        "series",
        "xaxis",
        "yaxis"
      ]
    },
    "headCountChange": {
      "type": "object",
      "properties": {
        "legend": {
          "type": "object",
          "properties": {
            "data": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "data"
          ]
        },
        "series": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "data": {
                "type": "array",
                "items": {
                  "type": "number"
                }
              },
              "values": {
                "type": "array",
                "items": {}
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "data",
              "values",
              "type"
            ]
          }
        },
        "xaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "type",
            "data"
          ]
        },
        "yaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "type",
            "data"
          ]
        }
      },
      "required": [
        "legend",
        "series",
        "xaxis",
        "yaxis"
      ]
    },
    "gender": {
      "type": "object",
      "properties": {
        "legend": {
          "type": "object",
          "properties": {
            "data": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "data"
          ]
        },
        "series": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "data": {
                "type": "array",
                "items": {
                  "type": "number"
                }
              },
              "values": {
                "type": "array",
                "items": {}
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "data",
              "values",
              "type"
            ]
          }
        },
        "xaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "type",
            "data"
          ]
        },
        "yaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "type",
            "data"
          ]
        }
      },
      "required": [
        "legend",
        "series",
        "xaxis",
        "yaxis"
      ]
    },
    "pyramid": {
      "type": "object",
      "properties": {
        "legend": {
          "type": "object",
          "properties": {
            "data": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "data"
          ]
        },
        "series": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "data": {
                "type": "array",
                "items": {}
              },
              "values": {
                "type": "array",
                "items": {}
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "data",
              "values",
              "type"
            ]
          }
        },
        "xaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "type",
            "data"
          ]
        },
        "yaxis": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "data": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "type",
            "data"
          ]
        }
      },
      "required": [
        "legend",
        "series",
        "xaxis",
        "yaxis"
      ]
    }
  },
  "required": [
    "aop",
    "headCountChange",
    "gender",
    "pyramid"
  ]
}

=== Yogesh111994/APITestingFramework2024/src/test/resources/responsetestdata/structuredeepdiveresponsedata.json
[
	{
	    "aop": {
	        "legend": {
	            "data": [
	                "AOP",
	                "Occupied Position",
	                "Fill Rate %"
	            ]
	        },
	        "series": [
	            {
	                "name": "AOP",
	                "data": [
	                    19,
	                    21,
	                    22,
	                    27,
	                    26,
	                    26
	                ],
	                "values": [],
	                "type": "bar"
	            },
	            {
	                "name": "Occupied Position",
	                "data": [
	                    17,
	                    20,
	                    20,
	                    26,
	                    25,
	                    25
	                ],
	                "values": [],
	                "type": "bar"
	            },
	            {
	                "name": "Fill Rate %",
	                "data": [
	                    89,
	                    95,
	                    91,
	                    96,
	                    96,
	                    96
	                ],
	                "values": [],
	                "type": "line"
	            }
	        ],
	        "xaxis": {
	            "type": "",
	            "data": [
	                "Oct - 2023",
	                "Nov - 2023",
	                "Dec - 2023",
	                "Jan - 2024",
	                "Feb - 2024",
	                "Mar - 2024"
	            ]
	        },
	        "yaxis": {
	            "type": "value",
	            "data": []
	        }
	    },
	    "headCountChange": {
	        "legend": {
	            "data": [
	                "Hires",
	                "Attrition",
	                "Headcount Change"
	            ]
	        },
	        "series": [
	            {
	                "name": "Hires",
	                "data": [
	                    0,
	                    1,
	                    0,
	                    1,
	                    0,
	                    0
	                ],
	                "values": [],
	                "type": "bar"
	            },
	            {
	                "name": "Attrition",
	                "data": [
	                    0,
	                    0,
	                    0,
	                    0,
	                    0,
	                    0
	                ],
	                "values": [],
	                "type": "bar"
	            },
	            {
	                "name": "Headcount Change",
	                "data": [
	                    0,
	                    1,
	                    0,
	                    1,
	                    0,
	                    0
	                ],
	                "values": [],
	                "type": "line"
	            }
	        ],
	        "xaxis": {
	            "type": "",
	            "data": [
	                "Oct - 2023",
	                "Nov - 2023",
	                "Dec - 2023",
	                "Jan - 2024",
	                "Feb - 2024",
	                "Mar - 2024"
	            ]
	        },
	        "yaxis": {
	            "type": "value",
	            "data": []
	        }
	    },
	    "gender": {
	        "legend": {
	            "data": [
	                "Male",
	                "Female",
	                "Female %"
	            ]
	        },
	        "series": [
	            {
	                "name": "Male",
	                "data": [
	                    17,
	                    20,
	                    20,
	                    26,
	                    25,
	                    25
	                ],
	                "values": [],
	                "type": "bar"
	            },
	            {
	                "name": "Female",
	                "data": [
	                    0,
	                    0,
	                    0,
	                    0,
	                    0,
	                    0
	                ],
	                "values": [],
	                "type": "bar"
	            },
	            {
	                "name": "Female %",
	                "data": [
	                    0,
	                    0,
	                    0,
	                    0,
	                    0,
	                    0
	                ],
	                "values": [],
	                "type": "line"
	            }
	        ],
	        "xaxis": {
	            "type": "",
	            "data": [
	                "Oct - 2023",
	                "Nov - 2023",
	                "Dec - 2023",
	                "Jan - 2024",
	                "Feb - 2024",
	                "Mar - 2024"
	            ]
	        },
	        "yaxis": {
	            "type": "value",
	            "data": []
	        }
	    },
	    "pyramid": {
	        "legend": {
	            "data": [
	                "Male",
	                "Female"
	            ]
	        },
	        "series": [
	            {
	                "name": "Male",
	                "data": [
	                    1,
	                    19,
	                    5
	                ],
	                "values": [],
	                "type": "bar"
	            },
	            {
	                "name": "Female",
	                "data": [
	                    0,
	                    0,
	                    0
	                ],
	                "values": [],
	                "type": "bar"
	            }
	        ],
	        "xaxis": {
	            "type": "value",
	            "data": []
	        },
	        "yaxis": {
	            "type": "",
	            "data": [
	                "Grade 8",
	                "Grade 9",
	                "Grade 11"
	            ]
	        }
	    }
	}
]
